FROM node:22-alpine AS frontend

# Working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# RUN npm cache clean --force

# Install dependencies
RUN npm install



# RUN npm config set registry https://registry.npmjs.org/ && \
#     npm config set fetch-retries 3 && \
#     npm config set fetch-retry-factor 10 && \
#     npm config set fetch-retry-mintimeout 10000 && \
#     npm config set fetch-retry-maxtimeout 60000 && \
#     npm install --no-audit --no-fund --verbose

# Copy the rest of the file
COPY . .

EXPOSE 5173

# Start the application
CMD ["npm", "run", "dev"]
