FROM node:22-alpine AS development

# Working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# RUN npm cache clean --force
# RUN npm ci --production

# Copy the rest of the file
COPY . .

# Start the application
CMD ["npm", "run", "start:dev"]

